// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmAPEFkK4RgXyuYvQRcu3u4pOTptqlQQc',
    appId: '1:266873692916:web:f45486bdd86ef011fdf4a1',
    messagingSenderId: '266873692916',
    projectId: 'flutter-project-try',
    authDomain: 'flutter-project-try.firebaseapp.com',
    storageBucket: 'flutter-project-try.appspot.com',
    measurementId: 'G-DLW6HV748H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRc1sMdr8SByFE5gKPtDHKiH68grUK0Rs',
    appId: '1:266873692916:android:05314a2974244efffdf4a1',
    messagingSenderId: '266873692916',
    projectId: 'flutter-project-try',
    storageBucket: 'flutter-project-try.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClBMXluOUIqCe-O7GJbB3tJN80y8Q5M7E',
    appId: '1:266873692916:ios:275a382fd5b90a81fdf4a1',
    messagingSenderId: '266873692916',
    projectId: 'flutter-project-try',
    storageBucket: 'flutter-project-try.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClBMXluOUIqCe-O7GJbB3tJN80y8Q5M7E',
    appId: '1:266873692916:ios:275a382fd5b90a81fdf4a1',
    messagingSenderId: '266873692916',
    projectId: 'flutter-project-try',
    storageBucket: 'flutter-project-try.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmAPEFkK4RgXyuYvQRcu3u4pOTptqlQQc',
    appId: '1:266873692916:web:c2d950aa483c16f7fdf4a1',
    messagingSenderId: '266873692916',
    projectId: 'flutter-project-try',
    authDomain: 'flutter-project-try.firebaseapp.com',
    storageBucket: 'flutter-project-try.appspot.com',
    measurementId: 'G-2QKVNXZKJ2',
  );
}
